export const DEFAULT_STUDIO_ID = 'main-studio';
export const SETTINGS_SCHEMA_VERSION = 1;

export const settingsSectionKeys = [
  'studioProfile',
  'operationalPolicy',
  'bookingPolicy',
  'pricingPolicy',
  'billingPolicy',
  'bookkeepingPolicy',
  'inventoryPolicy',
  'customerPolicy',
  'notificationPolicy',
  'appearancePolicy',
  'securityPolicy',
  'dataPolicy',
  'systemPolicy',
  'featureFlags',
];

export const defaultStudioSettings = {
  id: DEFAULT_STUDIO_ID,
  schemaVersion: SETTINGS_SCHEMA_VERSION,
  studioId: DEFAULT_STUDIO_ID,
  studioProfile: {
    studioName: '37 Music Studio',
    legalName: '',
    address: '',
    city: '',
    province: '',
    country: 'Indonesia',
    phone: '',
    whatsapp: '',
    email: '',
    website: '',
    instagram: '',
    tiktok: '',
    youtube: '',
    logoUrl: '',
    receiptLogoUrl: '',
    invoiceLogoUrl: '',
    timezone: 'Asia/Jakarta',
    locale: 'id-ID',
    currency: 'IDR',
    taxId: '',
    businessRegistration: '',
  },
  operationalPolicy: {
    timezone: 'Asia/Jakarta',
    weeklyHours: {
      monday: { open: true, start: '10:00', end: '22:00' },
      tuesday: { open: true, start: '10:00', end: '22:00' },
      wednesday: { open: true, start: '10:00', end: '22:00' },
      thursday: { open: true, start: '10:00', end: '22:00' },
      friday: { open: true, start: '10:00', end: '23:00' },
      saturday: { open: true, start: '09:00', end: '23:00' },
      sunday: { open: true, start: '09:00', end: '22:00' },
    },
    holidayDates: [],
    blackoutDates: [],
    specialOpenDates: [],
    slotMinutes: 60,
    bufferMinutes: 0,
    minLeadMinutes: 60,
    maxAdvanceDays: 45,
    gracePeriodMinutes: 15,
    defaultSessionDurationMinutes: 60,
    allowBookingOutsideHours: false,
    showClosedDaysInCalendar: true,
  },
  bookingPolicy: {
    allowOverlap: false,
    requireCustomerName: true,
    requireCustomerPhone: true,
    requireCustomerEmail: false,
    requireDeposit: false,
    defaultDepositType: 'fixed',
    defaultDepositAmount: 0,
    defaultBookingStatus: 'pending',
    defaultPaymentStatus: 'unpaid',
    autoCancelUnpaid: false,
    autoCancelAfterMinutes: 0,
    cancellationAllowed: true,
    cancellationCutoffHours: 3,
    noShowEnabled: false,
    noShowThresholdMinutes: 30,
    statusColorMapping: {},
    bookingReminderEnabled: false,
    bookingNoteRequired: false,
    operatorNoteRequired: false,
    customerSourceRequired: false,
  },
  pricingPolicy: {
    defaultHourlyRate: 120000,
    weekendHourlyRate: 120000,
    peakHourRate: 0,
    offPeakRate: 0,
    overtimeRate: 120000,
    minimumDurationMinutes: 60,
    roundingMode: 'none',
    taxEnabled: false,
    taxRate: 0,
    serviceFeeEnabled: false,
    serviceFeeType: 'fixed',
    serviceFeeAmount: 0,
    discountEnabled: true,
    maxManualDiscount: 0,
    packages: [],
    addOns: [],
    bundleOffers: [],
  },
  billingPolicy: {
    invoicePrefix: 'INV',
    receiptPrefix: 'RCPT',
    numberingReset: 'monthly',
    nextInvoiceNumberPreview: '',
    defaultDueDays: 0,
    defaultInvoiceStatus: 'unpaid',
    paymentMethods: [
      { id: 'cash', label: 'Cash', active: true, accountId: 'cash', requiresReference: false, iconKey: 'cash' },
      { id: 'transfer', label: 'Transfer', active: true, accountId: 'transfer', requiresReference: true, iconKey: 'bank' },
      { id: 'qris', label: 'QRIS', active: true, accountId: 'qris', requiresReference: true, iconKey: 'qris' },
    ],
    receiptFooter: 'Terima kasih sudah menggunakan 37 Music Studio.',
    invoiceTerms: '',
    printPaperSize: 'thermal-80',
    showLogoOnReceipt: false,
    showOperatorOnReceipt: true,
    showCustomerPhoneOnReceipt: true,
    autoCreateInvoiceFromBooking: false,
    autoSyncBookingPayment: false,
    allowPartialPayment: true,
    allowOverpayment: false,
    roundingMode: 'none',
    defaultPOSCategory: 'manual_pos',
  },
  bookkeepingPolicy: {
    accounts: [
      { id: 'cash', name: 'Cash', type: 'cash', active: true, openingBalance: 0, colorTone: 'cyan' },
      { id: 'transfer', name: 'Bank Transfer', type: 'bank', active: true, openingBalance: 0, colorTone: 'purple' },
      { id: 'qris', name: 'QRIS', type: 'ewallet', active: true, openingBalance: 0, colorTone: 'cyan' },
    ],
    incomeCategories: [
      { id: 'studio_rent', name: 'Sewa Studio', type: 'income', active: true, reportGroup: 'studio', colorTone: 'cyan' },
      { id: 'pos_sale', name: 'Penjualan POS', type: 'income', active: true, reportGroup: 'pos', colorTone: 'cyan' },
    ],
    expenseCategories: [
      { id: 'maintenance', name: 'Perawatan Alat', type: 'expense', active: true, reportGroup: 'operational', colorTone: 'accent' },
      { id: 'utilities', name: 'Listrik & Internet', type: 'expense', active: true, reportGroup: 'operational', colorTone: 'accent' },
    ],
    transferCategories: [
      { id: 'transfer', name: 'Transfer Internal', type: 'transfer', active: true, reportGroup: 'internal', colorTone: 'purple' },
    ],
    paymentMethodAccountMapping: {
      cash: 'cash',
      transfer: 'transfer',
      qris: 'qris',
    },
    autoImportBilling: false,
    requireReviewBeforeImport: true,
    allowEditImportedEntry: false,
    deleteMode: 'void-only',
    voidReasonRequired: true,
    monthlyClosingEnabled: false,
    monthlyClosingDay: 31,
    lockedMonths: [],
    openingBalanceByAccount: {},
    defaultIncomeAccount: 'cash',
    defaultExpenseAccount: 'cash',
    defaultBillingIncomeCategory: 'studio_rent',
    defaultPOSIncomeCategory: 'pos_sale',
    defaultMaintenanceExpenseCategory: 'maintenance',
  },
  inventoryPolicy: {
    assetCategories: ['Instrument', 'Amplifier', 'Microphone', 'Cable', 'Recording', 'Accessory'],
    consumableCategories: ['Cable', 'String', 'Drumstick'],
    conditionLabels: ['Excellent', 'Good', 'Poor'],
    lowStockThresholdDefault: 1,
    allowNegativeStock: false,
    requireStockMovementReason: true,
    maintenanceReminderDays: 7,
    defaultMaintenanceIntervalDays: 30,
    warrantyReminderDays: 30,
    requireMaintenanceNotes: true,
    assetCodePrefix: 'ASSET',
    depreciationEnabled: false,
    depreciationMethod: 'none',
    maintenanceStatusLabels: ['ready', 'maintenance', 'retired'],
  },
  customerPolicy: {
    requirePhone: true,
    requireEmail: false,
    allowDuplicatePhone: false,
    duplicateDetectionMode: 'warn',
    defaultCustomerSource: 'booking',
    customerTags: [],
    customerLevels: [],
    allowCustomerNotes: true,
    dataRetentionMonths: 0,
    birthdayReminderEnabled: false,
    inactiveCustomerAfterDays: 90,
    showSpendingSummary: true,
    showBillingHistory: true,
  },
  notificationPolicy: {
    bookingReminderEnabled: false,
    bookingReminderBeforeMinutes: 60,
    bookingReminderTemplate: '',
    invoiceReminderEnabled: false,
    invoiceReminderAfterDays: 1,
    invoiceReminderTemplate: '',
    paymentReceivedTemplate: '',
    bookingCancelledTemplate: '',
    lowStockAlertEnabled: true,
    maintenanceAlertEnabled: true,
    dailySummaryEnabled: false,
    dailySummaryTime: '21:00',
    operatorMentionEnabled: false,
    whatsappTemplateMode: 'manual',
  },
  appearancePolicy: {
    defaultTheme: 'dark',
    defaultDensity: 'comfortable',
    allowUserOverride: true,
    compactTables: false,
    reducedMotion: false,
    financialPrivacyMask: false,
    defaultAdminRoute: '/admin/bookings',
    sidebarDefaultCollapsed: false,
    mobileBottomNavBehavior: 'fixed',
    showCommandBarHints: true,
    showAdvancedBadges: true,
    dashboardDensity: 'comfortable',
    tableRowDensity: 'comfortable',
    receiptPrintTheme: 'default',
  },
  securityPolicy: {
    allowedAdminEmails: [],
    roleLabels: ['Owner', 'Manager', 'Operator', 'Viewer'],
    requireVerifiedEmail: false,
    sensitiveActionConfirmation: true,
    requireReasonForDangerousAction: true,
    auditSettingsChanges: true,
    sessionWarningText: '',
    maxFailedLoginDisplayOnly: 5,
    ownerEmail: '',
    emergencyContact: '',
  },
  dataPolicy: {
    exportEnabled: true,
    importEnabled: true,
    backupSnapshotEnabled: false,
    localFallbackEnabled: true,
    clearLocalFallbackRequiresConfirmation: true,
    resetSettingsRequiresConfirmation: true,
    unknownImportFieldsMode: 'warn',
  },
  systemPolicy: {
    diagnosticsEnabled: true,
    copyDiagnosticReportEnabled: true,
    troubleshootingGuideUrl: '',
  },
  featureFlags: {
    enableBookkeepingReports: true,
    enableBillingImportToBookkeeping: true,
    enableInventoryMaintenanceScheduler: true,
    enableCustomerBillingHistory: true,
    enablePushNotifications: false,
    enablePublicBookingPage: false,
    enableAdvancedRoles: false,
    enableDataExport: true,
    enableSettingsAuditPanel: true,
    enableReceiptLogo: false,
    enablePricingPackages: false,
    enableOperationalHoursValidation: false,
  },
  createdAt: '',
  updatedAt: '',
  updatedBy: {
    uid: '',
    email: '',
    displayName: '',
  },
};

export function getDefaultStudioSettings() {
  return structuredClone(defaultStudioSettings);
}
